Refactor Dockerfile.dev to improve dependency installation process and streamline development setup. Introduce multi-stage builds with separate stages for dependencies and development, allowing for more efficient image creation. Update CMD to use npm run dev for starting the application.

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -1,18 +1,28 @@
-FROM node:20
+# syntax=docker.io/docker/dockerfile:1
+
+FROM node:20-alpine AS base
+
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 
 WORKDIR /app
 
-# Copy package files
-COPY ./website/package.json ./
-COPY ./website/package-lock.json ./
+# Install dependencies based on the preferred package manager
+COPY website/package.json website/yarn.lock* website/package-lock.json* website/pnpm-lock.yaml* website/.npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+  elif [ -f package-lock.json ]; then npm ci --legacy-peer-deps; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Install dependencies with verbose logging
-RUN npm install --legacy-peer-deps --loglevel verbose
-
-ARG DOMAIN_CONFIG_PATH
-
-ENV DOMAIN_CONFIG_PATH=$DOMAIN_CONFIG_PATH
+# 2. Development image
+FROM base AS dev
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 
 EXPOSE 3000
 
-CMD ["npm", "run", "dev"] 
+CMD npm run dev
